"""State-space relationship and arbitrage research helpers."""

from oqp.research.state_space.base_filter import (
    StateSpaceArtifact,
    StateSpaceFilter,
    StateSpaceSchema,
    dataclass_to_dict,
)
from oqp.research.state_space.diagnostics import (
    coefficient_columns,
    summarize_dual_kalman_output,
)
from oqp.research.state_space.dual_kalman_regression import (
    DualKalmanRegression,
    DualKalmanRegressionConfig,
)
from oqp.research.state_space.feature_adapter import (
    build_dual_kalman_features,
    save_dual_kalman_feature_artifact,
)
from oqp.research.state_space.opportunity_scan import (
    ARBITRAGE_CALENDAR,
    ARBITRAGE_CROSS_PRODUCT,
    ARBITRAGE_STATISTICAL,
    DataAuditConfig,
    OpportunityScanConfig,
    build_asset_metadata,
    classify_arbitrage_type,
    compute_data_audit,
    construct_spread_for_candidate,
    normalize_daily_market_frame,
    run_opportunity_scan,
    selected_candidate_config,
)
from oqp.research.state_space.opportunity_scoring import (
    bounded_score,
    cost_score,
    dislocation_score,
    interpret_candidate,
    liquidity_score_from_rank,
    mean_reversion_score,
    score_opportunity,
    stability_score,
)
from oqp.research.state_space.relationship_lab import (
    RelationshipLabConfig,
    available_tickers,
    build_relationship_frame,
    list_daily_price_files,
    load_daily_price_frame,
    relationship_summary,
    run_relationship_dkf,
)
from oqp.research.state_space.spread_models import (
    SPREAD_CONTRACT_VALUE,
    SPREAD_LINEAR_PRICE,
    SPREAD_PRICE_RATIO,
    SPREAD_RETURN_RESIDUAL,
    SpreadModelConfig,
    build_price_matrix,
    construct_pair_spread,
    contract_multipliers_for_pair,
    estimate_half_life,
    estimate_ols_beta,
    latest_spread_summary,
    log_return_matrix,
    rolling_zscore,
    simple_spread_backtest,
)

__all__ = [
    "ARBITRAGE_CALENDAR",
    "ARBITRAGE_CROSS_PRODUCT",
    "ARBITRAGE_STATISTICAL",
    "DataAuditConfig",
    "DualKalmanRegression",
    "DualKalmanRegressionConfig",
    "OpportunityScanConfig",
    "RelationshipLabConfig",
    "SPREAD_CONTRACT_VALUE",
    "SPREAD_LINEAR_PRICE",
    "SPREAD_PRICE_RATIO",
    "SPREAD_RETURN_RESIDUAL",
    "SpreadModelConfig",
    "StateSpaceArtifact",
    "StateSpaceFilter",
    "StateSpaceSchema",
    "available_tickers",
    "bounded_score",
    "build_asset_metadata",
    "build_price_matrix",
    "build_dual_kalman_features",
    "build_relationship_frame",
    "classify_arbitrage_type",
    "coefficient_columns",
    "compute_data_audit",
    "construct_pair_spread",
    "construct_spread_for_candidate",
    "contract_multipliers_for_pair",
    "cost_score",
    "dataclass_to_dict",
    "dislocation_score",
    "estimate_half_life",
    "estimate_ols_beta",
    "interpret_candidate",
    "latest_spread_summary",
    "liquidity_score_from_rank",
    "list_daily_price_files",
    "load_daily_price_frame",
    "log_return_matrix",
    "mean_reversion_score",
    "normalize_daily_market_frame",
    "relationship_summary",
    "rolling_zscore",
    "run_relationship_dkf",
    "run_opportunity_scan",
    "save_dual_kalman_feature_artifact",
    "score_opportunity",
    "selected_candidate_config",
    "simple_spread_backtest",
    "stability_score",
    "summarize_dual_kalman_output",
]
