from __future__ import annotations

OUTCOME_COLORS = {
    "Correct": "#00C853",
    "Failed": "#FF5252",
}
MIN_FLOW_IMBALANCE = 0.35
MIN_BOOK_IMBALANCE = 0.10
MIN_VOLUME_INTENSITY = 3.0
MIN_RESILIENCE_TICKS = 0.0
BREAKDOWN_MIN_VOLUME_INTENSITY = 2.0
BREAKDOWN_MAX_BOOK_IMBALANCE = 0.10
BREAKDOWN_MAX_ROLLING_MID_MOVE = -5.0
BREAKDOWN_MIN_PRICE_SHOCK = 10.0
RTV_FAST_WINDOW_TICKS = 6
RTV_SLOW_WINDOW_TICKS = 5_000
RTV_PERCENTILE = 0.99
RTV_MIN_FAST_MOVE_TICKS = 5.0
MAX_PLOT_POINTS = 20_000
EVENT_CLUSTER_GAP_TICKS = 1
HYPOTHESIS_KEYS = ["bullish", "bearish", "bearish_breakdown", "relative_velocity", "relative_velocity_fade"]
DEFAULT_HYPOTHESIS_KEY = "relative_velocity"
RESEARCH_SWEEP_HORIZONS = [30, 60, 120, 240, 480]
