#!/usr/bin/env python3
"""Build the private manager-facing research repository from an allowlist."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


REPO_ROOT = next(
    parent for parent in Path(__file__).resolve().parents
    if (parent / "pyproject.toml").is_file()
)

ROOT_FILES = (
    ".dockerignore",
    ".env.example",
    "ARCHITECTURE.md",
    "README.md",
    "pyproject.toml",
    "requirements.txt",
    "scripts/platform/export_manager_repository.py",
    "src/oqp/__init__.py",
    "src/oqp/research_runtime.py",
)

INCLUDED_TREES = (
    "apps/research_dashboard",
    "config",
    "departments/data_platform",
    "departments/research",
    "departments/risk",
    "docs",
    "notebooks/Phase_7_Research_Projects",
    "requirements",
    "scripts/data",
    "scripts/research",
    "src/oqp/commands",
    "src/oqp/config",
    "src/oqp/contracts",
    "src/oqp/data",
    "src/oqp/demo",
    "src/oqp/domain",
    "src/oqp/execution",
    "src/oqp/market",
    "src/oqp/native",
    "src/oqp/optimization",
    "src/oqp/options",
    "src/oqp/portfolio/__init__.py",
    "src/oqp/portfolio/allocation",
    "src/oqp/research",
    "src/oqp/risk",
    "src/oqp/ui",
    "tests/architecture",
    "tests/contracts",
    "tests/data",
    "tests/execution",
    "tests/optimization",
    "tests/options",
    "tests/research",
    "tests/risk",
)

EXCLUDED_PREFIXES = (
    "departments/middle_office",
    "departments/trading",
    "apps/ops_dashboard",
    "apps/money_dashboard",
    "apps/paper_trading_dashboard",
    "src/oqp/accounts",
    "src/oqp/brokers",
    "src/oqp/investing",
    "src/oqp/journal",
    "src/oqp/ops",
    "src/oqp/paper_trading",
    "src/oqp/qmt_connector",
    "scripts/ops",
    "scripts/trading",
    "runtime",
    "data",
    "logs",
    "output",
    "reports",
)

EXCLUDED_PARTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "execution_logs",
}

EXCLUDED_NAMES = {
    ".DS_Store",
    ".env",
    "api_keys.json",
    "fmp_config.json",
    "secrets.toml",
    "user_defaults.json",
    "watchlist.json",
}

EXCLUDED_SUFFIXES = {
    ".aux",
    ".blg",
    ".cert",
    ".crt",
    ".csv",
    ".db",
    ".duckdb",
    ".dylib",
    ".h5",
    ".hdf5",
    ".fdb_latexmk",
    ".fls",
    ".joblib",
    ".key",
    ".onnx",
    ".p12",
    ".parquet",
    ".pem",
    ".pfx",
    ".pkl",
    ".pt",
    ".pth",
    ".pyc",
    ".sqlite",
    ".sqlite3",
    ".synctex.gz",
}

MANAGER_GITIGNORE = """\
.env
.env.*
!.env.example
.venv/
venv/
__pycache__/
*.py[cod]
*.aux
*.blg
*.fdb_latexmk
*.fls
*.synctex.gz
.pytest_cache/
.mypy_cache/
.ruff_cache/
.ipynb_checkpoints/
.DS_Store
*.pem
*.key
*.cert
*.crt
*.p12
*.pfx
**/.streamlit/secrets.toml
**/api_keys.json
**/fmp_config.json
**/user_defaults.json
**/watchlist.json
runtime/
data/
logs/
output/
reports/
*.db
*.sqlite
*.sqlite3
*.duckdb
*.parquet
*.csv
*.pt
*.pth
*.pkl
*.joblib
*.onnx
*.h5
*.hdf5
build/
dist/
*.egg-info/
*.so
*.o
*.dylib
*.dll
"""

MANAGER_DOCKERIGNORE = """\
.git/
.gitignore
.DS_Store
.pytest_cache/
.mypy_cache/
.ruff_cache/
.ipynb_checkpoints/
__pycache__/
*.py[cod]
*.aux
*.blg
*.fdb_latexmk
*.fls
*.synctex.gz
.env
.env.*
!.env.example
.venv/
venv/
build/
dist/
*.egg-info/
runtime/
data/
logs/
output/
reports/
*.db
*.sqlite
*.sqlite3
*.duckdb
*.parquet
*.csv
*.pt
*.pth
*.pkl
*.joblib
*.onnx
*.h5
*.hdf5
*.pem
*.key
*.cert
*.crt
*.p12
*.pfx
**/.streamlit/secrets.toml
**/api_keys.json
**/fmp_config.json
**/user_defaults.json
**/watchlist.json
"""

BOUNDARY_DOCUMENT = """\
# Manager Research Repository Boundary

This private repository contains the research and backtesting surface needed
to inspect factors, sleeves, routers, risk overlays, strategy recipes,
optimisation, data contracts, and the research dashboard.

It intentionally excludes middle-office account aggregation, broker and paper
trading operations, portfolio reporting, operational dashboards, credentials,
runtime databases, vendor data, generated reports, model checkpoints, and
backtest artifacts.

Live factor and component implementations are included because this repository
is private. Transaction costs, execution assumptions, and data fingerprints
still belong in reproducible configuration; no local runtime state is copied.

The repository is generated by
`scripts/platform/export_manager_repository.py` in the source workspace. Its
commit history is independent from the public framework repository.
"""


def is_exportable(relative_path: Path) -> bool:
    """Return whether one allowlisted source file may enter the private export."""

    normalized = relative_path.as_posix()
    if any(
        normalized == prefix or normalized.startswith(f"{prefix}/")
        for prefix in EXCLUDED_PREFIXES
    ):
        return False
    if any(part in EXCLUDED_PARTS for part in relative_path.parts):
        return False
    if relative_path.name in EXCLUDED_NAMES:
        return False
    if relative_path.name.startswith(".env") and relative_path.name != ".env.example":
        return False
    if normalized.lower().endswith(tuple(EXCLUDED_SUFFIXES)):
        return False
    return True


def export_repository(
    destination: Path,
    *,
    source: Path = REPO_ROOT,
    clean: bool = False,
) -> tuple[int, int]:
    """Copy the manager allowlist while preserving an existing destination Git repo."""

    source = source.expanduser().resolve()
    destination = destination.expanduser().resolve()
    if not (source / "pyproject.toml").is_file():
        raise ValueError(f"source is not an OQP repository: {source}")
    if destination == source or source in destination.parents:
        raise ValueError("manager export destination must be outside the source repository")

    if destination.exists() and any(destination.iterdir()):
        if not clean:
            raise FileExistsError(
                f"destination is not empty; pass --clean to replace it: {destination}"
            )
        if not (destination / ".git").exists():
            raise ValueError(
                "--clean is allowed only for an existing Git repository"
            )
        for child in destination.iterdir():
            if child.name == ".git":
                continue
            if child.is_dir() and not child.is_symlink():
                shutil.rmtree(child)
            else:
                child.unlink()
    destination.mkdir(parents=True, exist_ok=True)

    copied_files = 0
    skipped_files = 0
    for relative_root in (*ROOT_FILES, *INCLUDED_TREES):
        root = source / relative_root
        if not root.exists():
            continue
        candidates = (root,) if root.is_file() else root.rglob("*")
        for candidate in candidates:
            if not candidate.is_file() or candidate.is_symlink():
                continue
            relative = candidate.relative_to(source)
            if not is_exportable(relative):
                skipped_files += 1
                continue
            target = destination / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(candidate, target)
            copied_files += 1

    (destination / ".gitignore").write_text(
        MANAGER_GITIGNORE,
        encoding="utf-8",
    )
    (destination / ".dockerignore").write_text(
        MANAGER_DOCKERIGNORE,
        encoding="utf-8",
    )
    (destination / "MANAGER_REPOSITORY_BOUNDARY.md").write_text(
        BOUNDARY_DOCUMENT,
        encoding="utf-8",
    )
    return copied_files, skipped_files


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export the private manager-facing OQP research repository.",
    )
    parser.add_argument("destination", type=Path)
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Replace an existing Git worktree while preserving its .git directory.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    copied, skipped = export_repository(
        args.destination,
        clean=bool(args.clean),
    )
    print(
        f"Manager repository export complete: {copied} files copied, "
        f"{skipped} private runtime/data artifacts skipped."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
