"""Investing research utilities shared by money dashboard pages."""

from oqp.investing.stock_valuation import (
    RATIO_CATEGORIES,
    VALUATION_MULTIPLE_COLUMNS,
    DCFValuation,
    PeerComparison,
    calculate_cagr,
    calculate_dcf_valuation,
    fetch_fmp_json,
    fetch_fundamental_data,
    fetch_peer_comparison,
    fetch_price_target_consensus,
    format_compact_currency,
    latest_statement_value,
    safe_num,
)
from oqp.investing.watchlist import (
    DEFAULT_INVESTING_STATE_DIR,
    DEFAULT_STOCK_WATCHLIST_PATH,
    LEGACY_STOCK_WATCHLIST_PATH,
    add_stock_watchlist_symbol,
    load_stock_watchlist,
    normalize_symbol,
    normalize_watchlist,
    remove_stock_watchlist_symbol,
    save_stock_watchlist,
)

__all__ = [
    "DCFValuation",
    "DEFAULT_INVESTING_STATE_DIR",
    "DEFAULT_STOCK_WATCHLIST_PATH",
    "LEGACY_STOCK_WATCHLIST_PATH",
    "PeerComparison",
    "RATIO_CATEGORIES",
    "VALUATION_MULTIPLE_COLUMNS",
    "add_stock_watchlist_symbol",
    "calculate_cagr",
    "calculate_dcf_valuation",
    "fetch_fmp_json",
    "fetch_fundamental_data",
    "fetch_peer_comparison",
    "fetch_price_target_consensus",
    "format_compact_currency",
    "latest_statement_value",
    "load_stock_watchlist",
    "normalize_symbol",
    "normalize_watchlist",
    "remove_stock_watchlist_symbol",
    "safe_num",
    "save_stock_watchlist",
]
