"""Risk analytics and hedging utilities."""

from oqp.risk.portfolio import (
    HedgeDiagnosis,
    InverseHedgePlan,
    PortfolioRiskSummary,
    average_true_range,
    black_scholes_greeks,
    broker_risk_table,
    concentration_table,
    enrich_position_risk,
    hedge_diagnosis,
    inverse_hedge_plan,
    micro_future_multiplier,
    position_multiplier,
    safe_float,
    summarize_portfolio_risk,
)
from oqp.risk.factor_breadth import (
    RiskBreadthConfig,
    compute_breadth_metrics,
    compute_log_return_matrix,
    compute_risk_factor_breadth,
    compute_rolling_breadth,
    extract_base_symbol,
    infer_component_labels,
    load_futures_daily_data,
    map_chinese_futures_sector,
    prepare_pca_matrix,
    run_covariance_pca,
)
from oqp.risk.live_factor_lab import (
    FACTOR_PROXY_DEFINITIONS,
    LiveFactorLabConfig,
    canonical_risk_symbol,
    combine_price_histories,
    compute_factor_proxy_lab,
    compute_pca_crowding_lab,
    exposure_symbols,
    factor_proxy_symbols,
)

__all__ = [
    "FACTOR_PROXY_DEFINITIONS",
    "HedgeDiagnosis",
    "InverseHedgePlan",
    "LiveFactorLabConfig",
    "PortfolioRiskSummary",
    "RiskBreadthConfig",
    "average_true_range",
    "black_scholes_greeks",
    "broker_risk_table",
    "canonical_risk_symbol",
    "combine_price_histories",
    "concentration_table",
    "compute_breadth_metrics",
    "compute_factor_proxy_lab",
    "compute_log_return_matrix",
    "compute_pca_crowding_lab",
    "compute_risk_factor_breadth",
    "compute_rolling_breadth",
    "enrich_position_risk",
    "exposure_symbols",
    "extract_base_symbol",
    "factor_proxy_symbols",
    "hedge_diagnosis",
    "infer_component_labels",
    "inverse_hedge_plan",
    "load_futures_daily_data",
    "map_chinese_futures_sector",
    "micro_future_multiplier",
    "prepare_pca_matrix",
    "position_multiplier",
    "run_covariance_pca",
    "safe_float",
    "summarize_portfolio_risk",
]
