"""Streamlit UI helpers shared by dashboards."""

from oqp.ui.streamlit_theme import (
    apply_ops_theme,
    language_selector,
    page_header,
    render_dark_area_chart,
    render_dark_bar_chart,
    render_dark_line_chart,
    render_dark_pie_chart,
    render_dark_table,
    nav_tiles,
    section_header,
    style_dark_plotly,
    tr,
)
from oqp.ui.translations import (
    RESEARCH_PAGE_TEXT,
    RESEARCH_TEXT,
    normalize_language,
    ops_tabs,
    ops_text,
    research_page_catalog,
    research_page_legacy_catalog,
    research_page_tabs,
    research_page_text,
    research_tabs,
    research_text,
    translate,
)

__all__ = [
    "apply_ops_theme",
    "language_selector",
    "normalize_language",
    "ops_tabs",
    "ops_text",
    "page_header",
    "render_dark_area_chart",
    "render_dark_bar_chart",
    "render_dark_line_chart",
    "render_dark_pie_chart",
    "render_dark_table",
    "nav_tiles",
    "RESEARCH_PAGE_TEXT",
    "RESEARCH_TEXT",
    "research_page_catalog",
    "research_page_legacy_catalog",
    "research_page_tabs",
    "research_page_text",
    "research_tabs",
    "research_text",
    "section_header",
    "style_dark_plotly",
    "tr",
    "translate",
]
